#!/bin/bash

VER7=$1
[ -z "$1" ] && VER7=`uname -r`

CONFIGTXT=/boot/config.txt
#VER7=`uname -r`
VER=${VER7/-v7/}
if [ "$VER7" = "$VER" ]; then
    VER7=${VER/+/-v7+}
    if [ "$VER7" = "$VER" ]; then
        VER7=${VER}-v7
    fi
fi

if grep -qe '^initramfs' $CONFIGTXT; then
  sed "s/initramfs initrd.pi1 /initramfs initrd.img-$VER /;t;
       s/initramfs initrd /initramfs initrd.img-$VER7 /;t;
       s/initramfs initrd.img-[^[:blank:]]*-v7[^[:blank:]]* /initramfs initrd.img-$VER7 /;t;
       s/initramfs initrd.img-[^[:blank:]]* /initramfs initrd.img-$VER /;t;" \
  -i $CONFIGTXT

else
  cat <<EOF >>$CONFIGTXT

[pi1]
initramfs initrd.img-$VER followkernel
[pi2]
initramfs initrd.img-$VER7 followkernel
[pi3]
initramfs initrd.img-$VER7 followkernel
[all]

EOF
fi
