variables:
#    TEMPLATE_DISABLE: "1"
    TEMPLATE_DEB_NAME: "unipi-tools"

include: 
    project: docker/template
    file: debian-pkg.yaml

##############################################################

job-build-buster:nano:
    extends: .build_for_buster
    tags: ['arm64']
    before_script: 
        - apt-get update
        - apt-get install -y axon-kernel-headers

job-build-stretch:nano:
    extends: .build_for_stretch
    tags: ['arm64']
    before_script: 
        - apt-get update
        - apt-get install -y axon-kernel-headers

job-build-buster:rpi:
    extends: .build_for_buster
    tags: ['armhf']
    before_script: 
        - apt-get update
        - apt-get install -y raspberrypi-kernel-headers

job-build-stretch:rpi:
    extends: .build_for_stretch
    tags: ['armhf']
    before_script: 
        - apt-get update
        - apt-get install -y raspberrypi-kernel-headers


test-deploy:
    extends: .deploy_test

release-deploy:
    extends: .deploy_master



