#! /usr/bin/dh-exec

unipi-common/systemd/system/* lib/systemd/system
unipi-common/systemd/system.conf.d/* lib/systemd/system.conf.d

unipi-common/udev/* lib/udev/rules.d

unipi-common/etc/initramfs/hooks/* etc/initramfs-tools/hooks
unipi-common/etc/initramfs/scripts/init-bottom/hwclock.sh etc/initramfs-tools/scripts/init-bottom
unipi-common/etc/initramfs/modules.d/* usr/share/initramfs-tools/modules.d
[linux-armhf] unipi-common/etc/initramfs/scripts/init-bottom/reinitialize_default_var  etc/initramfs-tools/scripts/init-bottom
[linux-armhf] unipi-common/etc/initramfs/scripts/init-bottom/setbootconfig.sh  etc/initramfs-tools/scripts/init-bottom
[linux-armhf] unipi-common/etc/initramfs/postinst/initrd-config etc/kernel/postinst.d

[linux-armhf] debian/tmp/boot/overlays/* boot/overlays

unipi-common/usr/bin/* usr/bin

debian/tmp/opt/unipi/bin/unipihost	opt/unipi/bin/
