'\" t
.\"     Title: modbus_get_float_dcba
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 06/26/2017
.\"    Manual: libmodbus Manual
.\"    Source: libmodbus v3.1.4
.\"  Language: English
.\"
.TH "MODBUS_GET_FLOAT_DCB" "3" "06/26/2017" "libmodbus v3\&.1\&.4" "libmodbus Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
modbus_get_float_dcba \- get a float value from 2 registers in DCBA byte order
.SH "SYNOPSIS"
.sp
\fBfloat modbus_get_float_dcba(const uint16_t *\fR\fB\fIsrc\fR\fR\fB);\fR
.SH "DESCRIPTION"
.sp
The \fBmodbus_get_float_dcba()\fR function shall get a float from 4 bytes in inversed Modbus format (DCBA order instead of ABCD)\&. The \fIsrc\fR array must be a pointer on two 16 bits values, for example, if the first word is set to 0x47F1 and the second to 0x2000, the float value will be read as 123456\&.0\&.
.SH "RETURN VALUE"
.sp
The function shall return a float\&.
.SH "SEE ALSO"
.sp
\fBmodbus_set_float_dcba\fR(3) \fBmodbus_get_float_abcd\fR(3) \fBmodbus_get_float_badc\fR(3) \fBmodbus_get_float_cdab\fR(3)
.SH "AUTHORS"
.sp
The libmodbus documentation was written by Stéphane Raimbault <stephane\&.raimbault@gmail\&.com>
