'\" t
.\"     Title: modbus_set_float_badc
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 06/26/2017
.\"    Manual: libmodbus Manual
.\"    Source: libmodbus v3.1.4
.\"  Language: English
.\"
.TH "MODBUS_SET_FLOAT_BAD" "3" "06/26/2017" "libmodbus v3\&.1\&.4" "libmodbus Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
modbus_set_float_badc \- set a float value in 2 registers using BADC byte order
.SH "SYNOPSIS"
.sp
\fBvoid modbus_set_float_badc(float \fR\fB\fIf\fR\fR\fB, uint16_t *\fR\fB\fIdest\fR\fR\fB);\fR
.SH "DESCRIPTION"
.sp
The \fBmodbus_set_float_badc()\fR function shall set a float to 4 bytes in swapped bytes Modbus format (BADC insted of ABCD)\&. The \fIdest\fR array must be pointer on two 16 bits values to be able to store the full result of the conversion\&.
.SH "RETURN VALUE"
.sp
There is no return values\&.
.SH "SEE ALSO"
.sp
\fBmodbus_get_float_badc\fR(3) \fBmodbus_set_float_abcd\fR(3) \fBmodbus_set_float_cdab\fR(3) \fBmodbus_set_float_dcba\fR(3)
.SH "AUTHORS"
.sp
The libmodbus documentation was written by Stéphane Raimbault <stephane\&.raimbault@gmail\&.com>
